# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none

pool:
  vmImage: ubuntu-latest


stages:
  - stage: validation
    displayName: 'validate the changes before deployment'
    jobs:
      - job: validatewebtemplate
        steps:
          - task: AzureCLI@2
            inputs:
              azureSubscription: 'sc-amtkmr-dev'
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: 'az deployment sub what-if -f main.bicep -l eastus -p main.parameters.json'
          
  - stage: dev
    displayName: 'Create Infra Dev Env'
    
    
    jobs:
      - deployment: devployBicep
        displayName: 'Deploy Bicep at Dev' 
        environment: dev
        workspace:
          clean: all
        strategy:
          runOnce:
            deploy:
              steps:
              - checkout: self
              - task: AzureCLI@2
                inputs:
                  azureSubscription: 'sc-amtkmr-dev'
                  scriptType: 'bash'
                  scriptLocation: 'inlineScript'
                  inlineScript: 'az deployment sub create -f main.bicep -l eastus -p main.parameters.json'
      

